### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by anthonyraf** [anthonyraf/anthonyraf#1]
Hi @jjlin526 👋, I just saw you went through my profile, could you leave a little star pls, I subscribed to you by the way.
Thanks. 😄

**Comment by uol-j-lin** [comment]
> Hi @jjlin526 👋, I just saw you went through my profile, could you leave a little star pls, I subscribed to you by the way.
> 
> Thanks. 😄 

Starred your README, feel free to do the same!
